### ISSUE TITLE
Camera flip

### ISSUE THREAD

**Issue by andreygaidzel** [basst314/ngx-webcam#61] opened 2019-08-22 18:33 UTC
On flag 'mirrorImage' you flip only css video, but not image. I fix it:

    const context2d = _canvas.getContext('2d');
    context2d.save();
    context2d.scale(-1, 1);
    context2d.drawImage(_video, _canvas.width * -1, 0, _canvas.width, _canvas.height);
    context2d.restore();

**Comment by basst314** [comment] 2019-09-19 16:11
Hi @andreygaidzel,

Thanks for raising this.
It has been an intentional decision to not mirror the captured image, since this aligns with common behavior in most smartphones today when taking a selfie.

Usually the preview is mirrored but the taken image is not. If required, app owners can easily mirror the emitted image.

I‘m closing this as it works as designed.

If you have any questions or concerns feel free to open a new issue.
Cheers!

**Closed by basst314** 2019-09-19 16:11 UTC

**Comment by Arjun-Shinojiya** [comment] 2019-10-15 06:14
@basst314 I am facing the same issue, the captured image is perfect but when I convert the base64 data into image then the captured image showing flip. Is there any way to get captured image without any flip?

**Comment by andreygaidzel** [comment] 2019-10-15 06:27
> @basst314 I am facing the same issue, the captured image is perfect but when I convert the base64 data into image then the captured image showing flip. Is there any way to get captured image without any flip?

I copy library code and costomize it with code on the previos message, because this library flip only CSS, but image dont changed. (sorry my ENG)

**Comment by Arjun-Shinojiya** [comment] 2019-10-15 06:40
@andreygaidzel Do you know any other way to stop the image from getting flip? because I cant do change in the library. If there is no other way then please let me know the line or the function in which I should as your code.Thank you
