### ISSUE TITLE
error in prod env

### ISSUE THREAD

**Issue by RoopaJain** [basst314/ngx-webcam#10] opened 2018-04-18 09:08 UTC
Not able to build the code base in production environment, shows the following error

ERROR in Error during template compile of 'WebcamModule'
Function calls are not supported in decorators but '?makeDecorator' was called
in 'NgModule'
'NgModule' calls '?makeDecorator'.

When i run the angualr 5 project in dev mode, build is successful
but when i choose Prod mode command as "ng build --aot", the above error pops up in CLI.

**Comment by vajjaharitha** [comment] 2018-04-18 11:15
Can't bind to 'trigger' since it isn't a known property of 'webcam'. ("
  
    <div>
        <webcam [ERROR ->][trigger]="triggerObservable" (imageCapture)="handleImage($event)"></webcam>
      <br/>
      <but"): ng:///AppModule/AppComponent.html@10:16
'webcam' is not a known element:


how to resolve these error 
can you please me

**Comment by basst314** [comment] 2018-06-07 15:46
Hi @RoopaJain,

is this issue still reproducable on your end?
I just tried `ng build --aot` on the demo-project and another project using the library and it builds successfully.

Which version of ngx-webcam and Angular are you using? Can you try with the latest version of ngx-webcam?

**Comment by basst314** [comment] 2018-06-12 15:47
Hi @RoopaJain,

I‘m closing this issue, as I haven‘t heard back from you and as there have already been new versions of ngx-webcam released in the meantime. So, please try again with the latest version.
If you‘re still experiencing errors, please feel free to open a new issue.

Thanks!

**Closed by basst314** 2018-06-12 15:47 UTC
