### ISSUE TITLE
Layout out in android browser

### ISSUE THREAD

**Issue by shoutao** [basst314/ngx-webcam#28] opened 2018-10-10 02:37 UTC
The layout is gone in android browser.

**Comment by shoutao** [comment] 2018-10-16 01:51
Hi, Sorry for not describing it clearly. I have attached two screen shots which are taken on Samsung s6 using the demo page.
![screenshot_20181016-094849](https://user-images.githubusercontent.com/11766189/46987921-d0fdef80-d128-11e8-8e93-a552adaa8501.png)
![screenshot_20181016-094836](https://user-images.githubusercontent.com/11766189/46987923-d1968600-d128-11e8-9cf3-01296d76e91a.png)

**Comment by basst314** [comment] 2018-10-16 01:55
Hi @shoutao,
Thanks for the screenshots. I will be looking into it as soon as possible.

**Comment by frederiksen** [comment] 2019-01-03 18:30
@shoutao try to rotate your android phone - when holding it horizontally, the web-cam component is filled correctly - when holding it normally - the web-cam component get's white boxes on the left/right sides.

**Comment by maurivillegas** [comment] 2019-01-04 21:01
Hi @basst314 
I'm facing the same problem on android smarthphones, please help us, the layout works ok on Horizontal, on Vertical Im having the same problem

**Comment by basst314** [comment] 2019-01-13 01:35
I can reproduce the issue on an iPhone when rotating the phone after the page was loaded. A refresh in any orientation fixes the issue. Seems to be an issue with the CSS not being applied properly because of the changing dimensions of the video element.

Looking into it...

**Comment by basst314** [comment] 2019-01-13 09:20
Found out that apparently Android devices return the wrong aspectRatio for portrait video streams. The aspectRatio always indicates a landscape video, therefore the bounding box is calculated incorrectly and the switch-button shows up in the wrong place.

working on a fix.

**Comment by basst314** [comment] 2019-01-14 06:15
Hi @shoutao and @frederiksen,

I'm happy to let you know that I published a fix for this issue in the current [release 0.2.2](https://github.com/basst314/ngx-webcam/releases/tag/0.2.2).

I tested the fix on all my devices (iOS+Android) and it resolved the bug!

In case something's still not working as expected, feel free to create a new issue here.

Cheers!

**Closed by basst314** 2019-01-14 06:15 UTC
Labels: bug
